### PR TITLE
use cuda 11 as base

### PR DESCRIPTION
**Pull request by Marek-CSS**

### CODE REVIEW

**Comment by mathematicalmichael** [comment]
howd it go?

**Comment by Marek-CSS** [comment]
hey, sorry that i opened the PR on this Repo, we are still testing..
It is the first project on our on Prem Cluster that uses GPUs and by now we have the issue that the GPUs do not show up within this jupyter notebook. But we are still troubleshooting.

I will let you know as soon as we know if it works or not.

**Comment by mathematicalmichael** [comment]
@Marek-CSS yeah it's a bit tricky. are you using consumer gpus or quadros? that may have an impact. also the way you launch the container matters. let me know if I can be of help if you get stuck

**Comment by mathematicalmichael** [comment]
I'm running CUDA 11 on my machine right now and the container I had running seemed to persist even when I upgraded my base system. I just ran a torch notebook and was able to verify the matrix multiplication happened on GPU

**Pull request closed without merging**
