### PR TITLE
Add starod / skaffold integration 

### PR DESCRIPTION
**Pull request by Leemoonsoo**
### What it is?

It adds "Run on staroid" button, so users can try to deploy this repository on the cloud with a few clicks.
More like the "Deploy to Heroku" button you can see in many Github repositories.
The difference is [staroid](https://staroid.com) provides Kubernetes cluster, GPU instance and [developers funding program](https://staroid.com/site/starrank).

### How to use?

Users can click a button to read me and run jupyer-gpu on the cloud.
Or if users have their own Kubernetes cluster, user can build and deploy to their cluster using included skaffold.yaml file, by running.

For example, deploy to local minikube in development mode.

```
skaffold dev -f .staroid/skaffold.yaml --port-forward -p minikube
```

### Motivation
Hi, I'm working on staroid, and open-source project https://github.com/open-datastudio/jupyter project on top of it.
Recently we enabled GPU support, based on gpu-jupyter repository. We could do it very quickly. Without gpu-jupyter repository, it would many weeks to figure out how to build a proper docker image. Appreciate all contributors here.

And we thought maybe we can contribute our integration to staroid to this repository.
But if this kind of integration is not what community wants, it's totally okay to just close this pull request.

### CODE REVIEW

**Comment by mathematicalmichael** [comment]
> ### What it is?
> 
> It adds "Run on staroid" button, so users can try to deploy this repository on the cloud with a few clicks.
> More like the "Deploy to Heroku" button you can see in many Github repositories.
> The difference is [staroid](https://staroid.com) provides Kubernetes cluster, GPU instance and [developers funding program](https://staroid.com/site/starrank).
> ### How to use?
> 
> Users can click a button to read me and run jupyer-gpu on the cloud.
> Or if users have their own Kubernetes cluster, user can build and deploy to their cluster using included skaffold.yaml file, by running.
> 
> For example, deploy to local minikube in development mode.
> 
> ```
> skaffold dev -f .staroid/skaffold.yaml --port-forward -p minikube
> ```
> 
> ### Motivation
> 
> Hi, I'm working on staroid, and open-source project https://github.com/open-datastudio/jupyter project on top of it.
> Recently we enabled GPU support, based on gpu-jupyter repository. We could do it very quickly. Without gpu-jupyter repository, it would many weeks to figure out how to build a proper docker image. Appreciate all contributors here.
> 
> And we thought maybe we can contribute our integration to staroid to this repository.
> But if this kind of integration is not what community wants, it's totally okay to just close this pull request.

yeah I noticed you open/close this the other day and checked out your website. Glad the docker image could be of help for your cloud service. going from local to cloud dev quickly by working in docker has been a lifesaver for me personally. Feel free to reach out to chat about your platform, it certainly peaks my interest. my contact info isn't hard to find.

**Comment by ChristophSchranz** [comment]
@Leemoonsoo that's a cool project, I'm looking forward to work with it!

**Comment by ChristophSchranz** [comment]
Unfortunately I can't add my card (Master Card) info: `Your card was declined.; code: card_declined: request-id: req_g9lmNFxMz2LcZ0`
What to do? May you send me a Promotional credit code for trying? I've followed you on Twitter for personal messages.

**Comment by Leemoonsoo** [comment]
@ChristophSchranz  Thanks! According to stripe payment system error code, 
Card decline could probably due to your bank think my service is not safe website :)
I checked my twitter but I'm not sure I got your twitter ID or personal message. Could you try DM me on twitter? my twitter handle is [@issuefreaks](https://twitter.com/issuefreaks). I can send some promotional credits.

@mathematicalmichael Thanks for the interest! I also tried to reach out to you via email. But my email might be in spam folder or lost :) Let me know if you need some promotional credits to test this out.

**Pull request merged**
