### PR TITLE
building slim and current default.

### PR DESCRIPTION
**Pull request by mathematicalmichael**
starting work on #27 

this initial PR replaces the current workflow with two in parallel which check not only the integrity of the build options, but also that the image can actually build. 
I may or may not keep the "split files" approach. Can't decide which I prefer. Thoughts? My thinking was that `main.yml` was growing very long.

### CODE REVIEW

**Comment by mathematicalmichael** [comment]
hm for some reason it's re-building itself when `start_local` is run. Not sure why it's not using cached layers, but I'll fix this with adding a makefile which separates building from running. `start_local` sounds like it should start something that exists, not build it.

**Comment by ChristophSchranz** [comment]
> 
> hm for some reason it's re-building itself when `start_local` is run. Not sure why it's not using cached layers, but I'll fix this with adding a makefile which separates building from running. `start_local` sounds like it should start something that exists, not build it.

Yes, `start_local` is meant to build and run the image in one line of code.

**Comment by ChristophSchranz** [comment]
Super that you found the time for this PR! 🎉

**Comment by mathematicalmichael** [comment]
ah! I wasn't expecting this to get merged. I want to finish a bunch more changes but wanted to get this started testing against your repo. This doesn't actually add any features to the repo. 

I'll open up another PR when I get more time to, but you can already `docker pull gupyter/minimal-notebook` (see the PR in my fork)

I still have to do the refactors so that we tag with the same patterns as the original docker stacks.

**Pull request merged**
