### PR TITLE
CI with Github Actions

### PR DESCRIPTION
**Pull request by mathematicalmichael**
I hope this can help with testing. Can eventually build on top to automate pushes to docker hub.

see https://github.com/mathematicalmichael/gpu-jupyter/pull/1 for status

### CODE REVIEW

**Comment by ChristophSchranz** [comment]
Cool script, thanks!

Is there also a way to push the built images as tagged images to Dockerhub?

**Comment by mathematicalmichael** [comment]
yes indeed! i figure we could work on that as a separate task. feel free to open up a new issue and we can work on it. mostly it entails you setting up github secrets to manage the login to do the push. I can point you in the direction of examples that do push to docker hub. I think the tagging scheme and such is a bit of an open design question (I did my best to give it a starting point with how I labeled the jobs).

**Comment by mathematicalmichael** [comment]
moreover, I think we should consider opening a PR on the docker-stacks repo with a link to this project in the README, since it is a "common" need, and perhaps start a convo about having it pushed to the `jupyter` dockerhub so that people can get it right from there rather than pointing to your docker username (or mine, for that matter). one less thing to remember for end-users

**Comment by ChristophSchranz** [comment]
I have asked to share it on Jupyter's docker-stacks, but the maintainers want their repository smaller (they already receive a bunch of issues and PRs). See the discussion [here](https://github.com/jupyter/docker-stacks/pull/1023#issuecomment-590293590)
They referred me to the [community stacks](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html#community-stacks). Maybe I should asked them again, as this project has gained more interest as expected. I've developed most of it in February!

Regarding the issue: We can either request them to merge PR https://github.com/iot-salzburg/gpu-jupyter/pull/18 (ensure correct permissions (enforced)), or we add it in `src/Dockerfile.header` (you should so that you get the commit ;) )

**Comment by mathematicalmichael** [comment]
ahhh interesting. I see. I've actually never seen the `selecting.md` file. I've largely been working off a pull I did long ago and really just updating to `latest` that they have as root images for the ones I built. Only this month did I start going through the updates made more recently (I can really only do upgrades over academic breaks anyway so as to keep the system fixed once the semester starts).

**Pull request merged**
